// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCopN4PfZtEZwUADRRt9UV4h9OGQjpi_kw',
    appId: '1:19712530786:web:6be0ab052108ebc28ab43b',
    messagingSenderId: '19712530786',
    projectId: 'trip-ae2d7',
    authDomain: 'trip-ae2d7.firebaseapp.com',
    databaseURL: 'https://trip-ae2d7-default-rtdb.firebaseio.com',
    storageBucket: 'trip-ae2d7.appspot.com',
    measurementId: 'G-WD8M7S70Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCM2Jnq47JBe-7-_2gprzjqI9fmub7PgE',
    appId: '1:19712530786:android:35c10f1f3b713c1d8ab43b',
    messagingSenderId: '19712530786',
    projectId: 'trip-ae2d7',
    databaseURL: 'https://trip-ae2d7-default-rtdb.firebaseio.com',
    storageBucket: 'trip-ae2d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-c2KrZDw-NNJqpRAgdr4TLFcI2xNPe0',
    appId: '1:19712530786:ios:6989ad28d10ff7bc8ab43b',
    messagingSenderId: '19712530786',
    projectId: 'trip-ae2d7',
    databaseURL: 'https://trip-ae2d7-default-rtdb.firebaseio.com',
    storageBucket: 'trip-ae2d7.appspot.com',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-c2KrZDw-NNJqpRAgdr4TLFcI2xNPe0',
    appId: '1:19712530786:ios:5b456062d648a5348ab43b',
    messagingSenderId: '19712530786',
    projectId: 'trip-ae2d7',
    databaseURL: 'https://trip-ae2d7-default-rtdb.firebaseio.com',
    storageBucket: 'trip-ae2d7.appspot.com',
    iosBundleId: 'com.example.driverapp.RunnerTests',
  );
}
